import os
import pathlib
from dotenv import load_dotenv
path = str(pathlib.Path(__file__).parents[2])
load_dotenv(path+"/.env")

DISCORD_BOT_TOKEN = os.getenv("DISCORD_BOT_TOKEN")
DISCORD_ADMIN_USERNAMES = os.getenv("DISCORD_ADMIN_USERNAMES")
DISCORD_COMMAND_PREFIX = os.getenv("DISCORD_COMMAND_PREFIX")
PALWORLD_RCON_HOST = os.getenv("PALWORLD_RCON_HOST")
PALWORLD_RCON_PORT = os.getenv("PALWORLD_RCON_PORT")
PALWORLD_RCON_PASSWORD = os.getenv("PALWORLD_RCON_PASSWORD")
DISCORD_DASHBOARD_CHANNEL_ID = os.getenv("DISCORD_DASHBOARD_CHANNEL_ID")
DISCORD_DASHBAORD_ONLINE_PLAYERS_MESSAGE_ID = os.getenv("DISCORD_DASHBAORD_ONLINE_PLAYERS_MESSAGE_ID")
DISCORD_LOG_CHANNEL_ID = os.getenv("DISCORD_LOG_CHANNEL_ID")
LANGUAGE = os.getenv("LANGUAGE")
SERVER_PATH = os.getenv("SERVER_PATH")
